name: Build Workflow

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install requirements
        run: |
          pip install -r src/requirements.txt
          
      - name: Run PyInstaller
        run: |
          python -m PyInstaller src/simple_backup.spec

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          $tags = git tag --list
          if (-not $tags) { $tag = "v1.0.0" } else { $tag = ($tags | Sort-Object -Descending)[0] }
          echo "LATEST_TAG=$tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Increment Tag
        id: increment_tag
        run: |
          $tag = $env:LATEST_TAG -replace "^v", ""
          $parts = $tag -split "\."
          $major = [int]$parts[0]
          $minor = [int]$parts[1]
          $patch = [int]$parts[2] + 1
          $new_tag = "v$major.$minor.$patch"
          echo "NEW_TAG=$new_tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: Release ${{ env.NEW_TAG }}
          body: |
            Newest release: **${{ env.NEW_TAG }}**
          draft: false
          prerelease: false
          
      - name: Upload Release Asset - EXE
        id: upload-release-asset-exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: dist/simple_backup.exe
          asset_name: SimpleBackup.exe
          asset_content_type: application/zip
